# Generated by Django 3.0.6 on 2020-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='displayed',
            field=models.CharField(default='Yes', max_length=5),
        ),
    ]
