# Generated by Django 3.0.6 on 2020-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_auto_20200608_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxexcl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxincl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxrule',
            field=models.CharField(choices=[('No tax', 'No tax'), ('Tax (9%)', 'Tax (9%)'), ('Tax (12%)', 'Tax (12%)'), ('Tax (15%)', 'Tax (15%)'), ('Tax (18%)', 'Tax (18%)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
