# Generated by Django 3.0.6 on 2020-06-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_auto_20200609_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='userName',
        ),
    ]
