# Generated by Django 3.0.6 on 2020-06-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_auto_20200610_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enableInvoice', models.CharField(default='Yes', max_length=100, null=True)),
                ('invoicePrefix', models.CharField(max_length=100, null=True)),
                ('invoiceNo', models.IntegerField(null=True)),
            ],
        ),
    ]
