# Generated by Django 3.0.6 on 2020-06-12 05:06

from django.db import migrations, models
import productapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0013_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='footerText',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='enableInvoice',
            field=models.CharField(default='Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceNo',
            field=models.CharField(blank=True, default=productapp.models.Invoice.increment_invoice_number, max_length=500, null=True),
        ),
    ]
